/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 9
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 16
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_increment = 1,
  sym_decrement = 2,
  sym_move_right = 3,
  sym_move_left = 4,
  sym_output = 5,
  sym_input = 6,
  sym_mov_keyword = 7,
  sym_zero_keyword = 8,
  sym_number = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  sym_source_file = 12,
  sym__instruction = 13,
  sym_loop = 14,
  aux_sym_source_file_repeat1 = 15,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_increment] = "increment",
  [sym_decrement] = "decrement",
  [sym_move_right] = "move_right",
  [sym_move_left] = "move_left",
  [sym_output] = "output",
  [sym_input] = "input",
  [sym_mov_keyword] = "mov_keyword",
  [sym_zero_keyword] = "zero_keyword",
  [sym_number] = "number",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym__instruction] = "_instruction",
  [sym_loop] = "loop",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_increment] = sym_increment,
  [sym_decrement] = sym_decrement,
  [sym_move_right] = sym_move_right,
  [sym_move_left] = sym_move_left,
  [sym_output] = sym_output,
  [sym_input] = sym_input,
  [sym_mov_keyword] = sym_mov_keyword,
  [sym_zero_keyword] = sym_zero_keyword,
  [sym_number] = sym_number,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym__instruction] = sym__instruction,
  [sym_loop] = sym_loop,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_increment] = {
    .visible = true,
    .named = true,
  },
  [sym_decrement] = {
    .visible = true,
    .named = true,
  },
  [sym_move_right] = {
    .visible = true,
    .named = true,
  },
  [sym_move_left] = {
    .visible = true,
    .named = true,
  },
  [sym_output] = {
    .visible = true,
    .named = true,
  },
  [sym_input] = {
    .visible = true,
    .named = true,
  },
  [sym_mov_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_zero_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__instruction] = {
    .visible = false,
    .named = true,
  },
  [sym_loop] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '+', 7,
        ',', 12,
        '-', 8,
        '.', 11,
        '<', 10,
        '>', 9,
        '[', 16,
        ']', 17,
        'm', 2,
        'z', 1,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == 'v') ADVANCE(13);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_increment);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_decrement);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_move_right);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_move_left);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_output);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_input);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_mov_keyword);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_zero_keyword);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_increment] = ACTIONS(1),
    [sym_decrement] = ACTIONS(1),
    [sym_move_right] = ACTIONS(1),
    [sym_move_left] = ACTIONS(1),
    [sym_output] = ACTIONS(1),
    [sym_input] = ACTIONS(1),
    [sym_mov_keyword] = ACTIONS(1),
    [sym_zero_keyword] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(8),
    [sym__instruction] = STATE(4),
    [sym_loop] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_increment] = ACTIONS(5),
    [sym_decrement] = ACTIONS(5),
    [sym_move_right] = ACTIONS(5),
    [sym_move_left] = ACTIONS(5),
    [sym_output] = ACTIONS(5),
    [sym_input] = ACTIONS(5),
    [sym_mov_keyword] = ACTIONS(5),
    [sym_zero_keyword] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym__instruction] = STATE(2),
    [sym_loop] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(9),
    [sym_increment] = ACTIONS(11),
    [sym_decrement] = ACTIONS(11),
    [sym_move_right] = ACTIONS(11),
    [sym_move_left] = ACTIONS(11),
    [sym_output] = ACTIONS(11),
    [sym_input] = ACTIONS(11),
    [sym_mov_keyword] = ACTIONS(11),
    [sym_zero_keyword] = ACTIONS(11),
    [sym_number] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(14),
    [anon_sym_RBRACK] = ACTIONS(9),
  },
  [STATE(3)] = {
    [sym__instruction] = STATE(5),
    [sym_loop] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_increment] = ACTIONS(17),
    [sym_decrement] = ACTIONS(17),
    [sym_move_right] = ACTIONS(17),
    [sym_move_left] = ACTIONS(17),
    [sym_output] = ACTIONS(17),
    [sym_input] = ACTIONS(17),
    [sym_mov_keyword] = ACTIONS(17),
    [sym_zero_keyword] = ACTIONS(17),
    [sym_number] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_RBRACK] = ACTIONS(19),
  },
  [STATE(4)] = {
    [sym__instruction] = STATE(2),
    [sym_loop] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_increment] = ACTIONS(23),
    [sym_decrement] = ACTIONS(23),
    [sym_move_right] = ACTIONS(23),
    [sym_move_left] = ACTIONS(23),
    [sym_output] = ACTIONS(23),
    [sym_input] = ACTIONS(23),
    [sym_mov_keyword] = ACTIONS(23),
    [sym_zero_keyword] = ACTIONS(23),
    [sym_number] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(7),
  },
  [STATE(5)] = {
    [sym__instruction] = STATE(2),
    [sym_loop] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_increment] = ACTIONS(23),
    [sym_decrement] = ACTIONS(23),
    [sym_move_right] = ACTIONS(23),
    [sym_move_left] = ACTIONS(23),
    [sym_output] = ACTIONS(23),
    [sym_input] = ACTIONS(23),
    [sym_mov_keyword] = ACTIONS(23),
    [sym_zero_keyword] = ACTIONS(23),
    [sym_number] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_RBRACK] = ACTIONS(25),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_increment] = ACTIONS(27),
    [sym_decrement] = ACTIONS(27),
    [sym_move_right] = ACTIONS(27),
    [sym_move_left] = ACTIONS(27),
    [sym_output] = ACTIONS(27),
    [sym_input] = ACTIONS(27),
    [sym_mov_keyword] = ACTIONS(27),
    [sym_zero_keyword] = ACTIONS(27),
    [sym_number] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(27),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_increment] = ACTIONS(29),
    [sym_decrement] = ACTIONS(29),
    [sym_move_right] = ACTIONS(29),
    [sym_move_left] = ACTIONS(29),
    [sym_output] = ACTIONS(29),
    [sym_input] = ACTIONS(29),
    [sym_mov_keyword] = ACTIONS(29),
    [sym_zero_keyword] = ACTIONS(29),
    [sym_number] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_RBRACK] = ACTIONS(29),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [14] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop, 3, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_brainfuckplus(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "brainfuckplus",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
