/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 14
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_increment = 1,
  sym_decrement = 2,
  sym_move_right = 3,
  sym_move_left = 4,
  sym_output = 5,
  sym_input = 6,
  sym_cellreference = 7,
  sym_mov_keyword = 8,
  sym_zero_keyword = 9,
  sym_add_keyword = 10,
  sym_sub_keyword = 11,
  sym_number = 12,
  anon_sym_DQUOTE = 13,
  aux_sym_string_token1 = 14,
  sym_string_escape = 15,
  sym_comment = 16,
  sym_block_comment = 17,
  anon_sym_LBRACK = 18,
  anon_sym_RBRACK = 19,
  sym_source_file = 20,
  sym__instruction = 21,
  sym_string = 22,
  sym_loop = 23,
  aux_sym_source_file_repeat1 = 24,
  aux_sym_string_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_increment] = "increment",
  [sym_decrement] = "decrement",
  [sym_move_right] = "move_right",
  [sym_move_left] = "move_left",
  [sym_output] = "output",
  [sym_input] = "input",
  [sym_cellreference] = "cellreference",
  [sym_mov_keyword] = "mov_keyword",
  [sym_zero_keyword] = "zero_keyword",
  [sym_add_keyword] = "add_keyword",
  [sym_sub_keyword] = "sub_keyword",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_string_escape] = "string_escape",
  [sym_comment] = "comment",
  [sym_block_comment] = "block_comment",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym__instruction] = "_instruction",
  [sym_string] = "string",
  [sym_loop] = "loop",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_increment] = sym_increment,
  [sym_decrement] = sym_decrement,
  [sym_move_right] = sym_move_right,
  [sym_move_left] = sym_move_left,
  [sym_output] = sym_output,
  [sym_input] = sym_input,
  [sym_cellreference] = sym_cellreference,
  [sym_mov_keyword] = sym_mov_keyword,
  [sym_zero_keyword] = sym_zero_keyword,
  [sym_add_keyword] = sym_add_keyword,
  [sym_sub_keyword] = sym_sub_keyword,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_string_escape] = sym_string_escape,
  [sym_comment] = sym_comment,
  [sym_block_comment] = sym_block_comment,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym__instruction] = sym__instruction,
  [sym_string] = sym_string,
  [sym_loop] = sym_loop,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_increment] = {
    .visible = true,
    .named = true,
  },
  [sym_decrement] = {
    .visible = true,
    .named = true,
  },
  [sym_move_right] = {
    .visible = true,
    .named = true,
  },
  [sym_move_left] = {
    .visible = true,
    .named = true,
  },
  [sym_output] = {
    .visible = true,
    .named = true,
  },
  [sym_input] = {
    .visible = true,
    .named = true,
  },
  [sym_cellreference] = {
    .visible = true,
    .named = true,
  },
  [sym_mov_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_zero_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_add_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_sub_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_string_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__instruction] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_loop] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '"', 30,
        '#', 24,
        '+', 18,
        ',', 23,
        '-', 19,
        '.', 22,
        ':', 4,
        '<', 21,
        '>', 20,
        '[', 42,
        '\\', 16,
        ']', 43,
        'a', 9,
        'm', 11,
        's', 14,
        'z', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == ':') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(38);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(40);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(2);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(3);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(3);
      END_STATE();
    case 7:
      if (lookahead == 'b') ADVANCE(28);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == 'u') ADVANCE(7);
      END_STATE();
    case 15:
      if (lookahead == 'v') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(39);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_increment);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_decrement);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_move_right);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_move_left);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_output);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_input);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_cellreference);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_mov_keyword);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_zero_keyword);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_add_keyword);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_sub_keyword);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '(') ADVANCE(32);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(37);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == ')') ADVANCE(36);
      if (lookahead == '\n' ||
          lookahead == '"' ||
          lookahead == '\\') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == ':') ADVANCE(35);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(38);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == ':') ADVANCE(38);
      if (lookahead == '\n' ||
          lookahead == '"' ||
          lookahead == '\\') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(32);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == ':') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(38);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == ':') ADVANCE(34);
      if (lookahead == '\n' ||
          lookahead == '"' ||
          lookahead == '\\') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(32);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_string_escape);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_increment] = ACTIONS(1),
    [sym_decrement] = ACTIONS(1),
    [sym_move_right] = ACTIONS(1),
    [sym_move_left] = ACTIONS(1),
    [sym_output] = ACTIONS(1),
    [sym_input] = ACTIONS(1),
    [sym_cellreference] = ACTIONS(1),
    [sym_mov_keyword] = ACTIONS(1),
    [sym_zero_keyword] = ACTIONS(1),
    [sym_add_keyword] = ACTIONS(1),
    [sym_sub_keyword] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_string_escape] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(13),
    [sym__instruction] = STATE(4),
    [sym_string] = STATE(4),
    [sym_loop] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_increment] = ACTIONS(7),
    [sym_decrement] = ACTIONS(7),
    [sym_move_right] = ACTIONS(7),
    [sym_move_left] = ACTIONS(7),
    [sym_output] = ACTIONS(7),
    [sym_input] = ACTIONS(7),
    [sym_cellreference] = ACTIONS(7),
    [sym_mov_keyword] = ACTIONS(7),
    [sym_zero_keyword] = ACTIONS(7),
    [sym_add_keyword] = ACTIONS(7),
    [sym_sub_keyword] = ACTIONS(7),
    [sym_number] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym__instruction] = STATE(2),
    [sym_string] = STATE(2),
    [sym_loop] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_increment] = ACTIONS(15),
    [sym_decrement] = ACTIONS(15),
    [sym_move_right] = ACTIONS(15),
    [sym_move_left] = ACTIONS(15),
    [sym_output] = ACTIONS(15),
    [sym_input] = ACTIONS(15),
    [sym_cellreference] = ACTIONS(15),
    [sym_mov_keyword] = ACTIONS(15),
    [sym_zero_keyword] = ACTIONS(15),
    [sym_add_keyword] = ACTIONS(15),
    [sym_sub_keyword] = ACTIONS(15),
    [sym_number] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(18),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym__instruction] = STATE(5),
    [sym_string] = STATE(5),
    [sym_loop] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_increment] = ACTIONS(24),
    [sym_decrement] = ACTIONS(24),
    [sym_move_right] = ACTIONS(24),
    [sym_move_left] = ACTIONS(24),
    [sym_output] = ACTIONS(24),
    [sym_input] = ACTIONS(24),
    [sym_cellreference] = ACTIONS(24),
    [sym_mov_keyword] = ACTIONS(24),
    [sym_zero_keyword] = ACTIONS(24),
    [sym_add_keyword] = ACTIONS(24),
    [sym_sub_keyword] = ACTIONS(24),
    [sym_number] = ACTIONS(24),
    [anon_sym_DQUOTE] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(26),
  },
  [STATE(4)] = {
    [sym__instruction] = STATE(2),
    [sym_string] = STATE(2),
    [sym_loop] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(28),
    [sym_increment] = ACTIONS(30),
    [sym_decrement] = ACTIONS(30),
    [sym_move_right] = ACTIONS(30),
    [sym_move_left] = ACTIONS(30),
    [sym_output] = ACTIONS(30),
    [sym_input] = ACTIONS(30),
    [sym_cellreference] = ACTIONS(30),
    [sym_mov_keyword] = ACTIONS(30),
    [sym_zero_keyword] = ACTIONS(30),
    [sym_add_keyword] = ACTIONS(30),
    [sym_sub_keyword] = ACTIONS(30),
    [sym_number] = ACTIONS(30),
    [anon_sym_DQUOTE] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(11),
  },
  [STATE(5)] = {
    [sym__instruction] = STATE(2),
    [sym_string] = STATE(2),
    [sym_loop] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_increment] = ACTIONS(30),
    [sym_decrement] = ACTIONS(30),
    [sym_move_right] = ACTIONS(30),
    [sym_move_left] = ACTIONS(30),
    [sym_output] = ACTIONS(30),
    [sym_input] = ACTIONS(30),
    [sym_cellreference] = ACTIONS(30),
    [sym_mov_keyword] = ACTIONS(30),
    [sym_zero_keyword] = ACTIONS(30),
    [sym_add_keyword] = ACTIONS(30),
    [sym_sub_keyword] = ACTIONS(30),
    [sym_number] = ACTIONS(30),
    [anon_sym_DQUOTE] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(32),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(34),
    [sym_increment] = ACTIONS(34),
    [sym_decrement] = ACTIONS(34),
    [sym_move_right] = ACTIONS(34),
    [sym_move_left] = ACTIONS(34),
    [sym_output] = ACTIONS(34),
    [sym_input] = ACTIONS(34),
    [sym_cellreference] = ACTIONS(34),
    [sym_mov_keyword] = ACTIONS(34),
    [sym_zero_keyword] = ACTIONS(34),
    [sym_add_keyword] = ACTIONS(34),
    [sym_sub_keyword] = ACTIONS(34),
    [sym_number] = ACTIONS(34),
    [anon_sym_DQUOTE] = ACTIONS(34),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(34),
    [anon_sym_RBRACK] = ACTIONS(34),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(36),
    [sym_increment] = ACTIONS(36),
    [sym_decrement] = ACTIONS(36),
    [sym_move_right] = ACTIONS(36),
    [sym_move_left] = ACTIONS(36),
    [sym_output] = ACTIONS(36),
    [sym_input] = ACTIONS(36),
    [sym_cellreference] = ACTIONS(36),
    [sym_mov_keyword] = ACTIONS(36),
    [sym_zero_keyword] = ACTIONS(36),
    [sym_add_keyword] = ACTIONS(36),
    [sym_sub_keyword] = ACTIONS(36),
    [sym_number] = ACTIONS(36),
    [anon_sym_DQUOTE] = ACTIONS(36),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(36),
    [anon_sym_RBRACK] = ACTIONS(36),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(38),
    [sym_increment] = ACTIONS(38),
    [sym_decrement] = ACTIONS(38),
    [sym_move_right] = ACTIONS(38),
    [sym_move_left] = ACTIONS(38),
    [sym_output] = ACTIONS(38),
    [sym_input] = ACTIONS(38),
    [sym_cellreference] = ACTIONS(38),
    [sym_mov_keyword] = ACTIONS(38),
    [sym_zero_keyword] = ACTIONS(38),
    [sym_add_keyword] = ACTIONS(38),
    [sym_sub_keyword] = ACTIONS(38),
    [sym_number] = ACTIONS(38),
    [anon_sym_DQUOTE] = ACTIONS(38),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(38),
    [anon_sym_RBRACK] = ACTIONS(38),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(40),
    [sym_increment] = ACTIONS(40),
    [sym_decrement] = ACTIONS(40),
    [sym_move_right] = ACTIONS(40),
    [sym_move_left] = ACTIONS(40),
    [sym_output] = ACTIONS(40),
    [sym_input] = ACTIONS(40),
    [sym_cellreference] = ACTIONS(40),
    [sym_mov_keyword] = ACTIONS(40),
    [sym_zero_keyword] = ACTIONS(40),
    [sym_add_keyword] = ACTIONS(40),
    [sym_sub_keyword] = ACTIONS(40),
    [sym_number] = ACTIONS(40),
    [anon_sym_DQUOTE] = ACTIONS(40),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(40),
    [anon_sym_RBRACK] = ACTIONS(40),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(42), 1,
      anon_sym_DQUOTE,
    STATE(11), 1,
      aux_sym_string_repeat1,
    ACTIONS(44), 2,
      aux_sym_string_token1,
      sym_string_escape,
    ACTIONS(46), 2,
      sym_comment,
      sym_block_comment,
  [15] = 4,
    ACTIONS(48), 1,
      anon_sym_DQUOTE,
    STATE(12), 1,
      aux_sym_string_repeat1,
    ACTIONS(46), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(50), 2,
      aux_sym_string_token1,
      sym_string_escape,
  [30] = 4,
    ACTIONS(52), 1,
      anon_sym_DQUOTE,
    STATE(12), 1,
      aux_sym_string_repeat1,
    ACTIONS(46), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(54), 2,
      aux_sym_string_token1,
      sym_string_escape,
  [45] = 2,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 15,
  [SMALL_STATE(12)] = 30,
  [SMALL_STATE(13)] = 45,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop, 3, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [57] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_brainfuckplus(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "brainfuckplus",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
